//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTracker_WindowsFormsApp.AuthServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthServiceReference.IAuthService")]
    public interface IAuthService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/SignIn", ReplyAction="http://tempuri.org/IAuthService/SignInResponse")]
        int SignIn(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/SignIn", ReplyAction="http://tempuri.org/IAuthService/SignInResponse")]
        System.Threading.Tasks.Task<int> SignInAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/SignUp", ReplyAction="http://tempuri.org/IAuthService/SignUpResponse")]
        int SignUp(string email, string password, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/SignUp", ReplyAction="http://tempuri.org/IAuthService/SignUpResponse")]
        System.Threading.Tasks.Task<int> SignUpAsync(string email, string password, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetAllUser", ReplyAction="http://tempuri.org/IAuthService/GetAllUserResponse")]
        System.Data.DataSet GetAllUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetAllUser", ReplyAction="http://tempuri.org/IAuthService/GetAllUserResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllUserAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthServiceChannel : ExpenseTracker_WindowsFormsApp.AuthServiceReference.IAuthService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthServiceClient : System.ServiceModel.ClientBase<ExpenseTracker_WindowsFormsApp.AuthServiceReference.IAuthService>, ExpenseTracker_WindowsFormsApp.AuthServiceReference.IAuthService {
        
        public AuthServiceClient() {
        }
        
        public AuthServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SignIn(string email, string password) {
            return base.Channel.SignIn(email, password);
        }
        
        public System.Threading.Tasks.Task<int> SignInAsync(string email, string password) {
            return base.Channel.SignInAsync(email, password);
        }
        
        public int SignUp(string email, string password, string username) {
            return base.Channel.SignUp(email, password, username);
        }
        
        public System.Threading.Tasks.Task<int> SignUpAsync(string email, string password, string username) {
            return base.Channel.SignUpAsync(email, password, username);
        }
        
        public System.Data.DataSet GetAllUser() {
            return base.Channel.GetAllUser();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllUserAsync() {
            return base.Channel.GetAllUserAsync();
        }
    }
}
